### ISSUE TITLE
floating point number comparisons

### ISSUE THREAD

**Issue by achubaty** [psolymos/intrval#17]
This is a useful package, I'm sad I hadn't started using it sooner!

Have you considered using more robust comparisons to deal with floating point number problems? See below.

```r
> x1 <- 0.5 - 0.3
> x2 <- 0.3 - 0.1
> 
> x1 %[]% c(0.2, 0.6)
[1] TRUE
> x2 %[]% c(0.2, 0.6)
[1] FALSE
```

My [`fpCompare`](https://github.com/PredictiveEcology/fpCompare) package deals with this for the basic relational operators, but having equivalent functionality to test intervals/ranges may be useful. Although, I recognize that this kind of change may break backwards compatibility / reproducibility without a mechanism (package option?) to use the alternate behaviour.

**Comment by psolymos** [comment]
@achubaty thanks for raising this issue. This is indeed a problem.

If I import the operators from fpCompare, and setting an option to `intrval.use_fpCompare=FALSE` for backwards compatibility. When this option is set to `TRUE`, I would use the fpCompare functions inside the internals with the set `fpCompare.tolerance` option.

**Comment by psolymos** [comment]
Hi @achubaty intrval treats operators more holistically than numeric to numeric, and I get errors when I simply replace `>=` with `%>=%` etc. That is because:

```R
1 %<=% 2
[1] TRUE

"a" %<=% "b"
Error in y + getOption("fpCompare.tolerance") : 
  non-numeric argument to binary operator

"a" <= "b"
[1] TRUE
```

I can do something like this in intrval:

```R
"%>=%" <- function(e1, e2) {
    if (is.numeric(e1) && is.numeric(e2))
        fpCompare::`%>=%`(e1, e2) else base::`>=`(e1, e2)
}
```

but I was wondering if this is an improvement that should be made in fpCompare instead?

See: https://github.com/psolymos/intrval/compare/master...fpCompare

**Comment by psolymos** [comment]
intrval_1.0-0.tar.gz is on its way to CRAN with fpCompare dependency

**Comment by achubaty** [comment]
Thanks Peter! Sorry I missed your earlier question on this - I will keep `fpCompare` to deal with floating point numbers and not worry about character or other types. Great to see this addition to `intrval`.
