### ISSUE TITLE
Interval-to-interval relations: some of them are not implemented?

### ISSUE THREAD

**Issue by mgacc0** [psolymos/intrval#4]
Some interval-to-interval relations 

Equal      | Not equal  | Less than  | Greater than
----------|------------|------------|----------------
 `%[0]%`  | `%)0(%`    | `%[<0]%`   | `%[0>]%`

are mentioned on the README but they are not implemented in [../blob/master/R/specials.R](../blob/master/R/specials.R) ?

(Great package! And congratulations...
I'm sure I will use it a lot. 👍 )

**Comment by psolymos** [comment]
Thanks for proofreading. It is supposed to be `o` and not `0`.

**Comment by psolymos** [comment]
Commit 95076baf1ef2a4d964eb086450c17db9b3dbe4e9 closes this issue.
